[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

# Serial monitor baud rate for computer terminal output
monitor_speed = 115200

# Allocate maximum possible space for application storage
board_build.partitions = huge_app.csv

# Exact registry IDs for automated package management
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    esphome/ESPAsyncWebServer-esphome @ ^3.2.2
    esphome/AsyncTCP-esphome @ ^2.1.3
    igorantolic/Ai Esp32 Rotary Encoder @ ^1.6
    
# Global project definitions
build_flags =
    -I include
    -D CORE_DEBUG_LEVEL=3
